services:
  - type: web
    name: font-system-backend
    env: php
    buildCommand: composer install
    startCommand: php -S 0.0.0.0:$PORT -t backend
    envVars:
      - key: MONGODB_URI
        sync: false